services:
    express-app:
        image: aezakml/express-app
        ports:
            - 8080:8080
        container_name: express-app

    watchtower:
        image: containrrr/watchtower
        command: 'express-app'
        depends_on:
            - express-app
        environment:
            - WATCHTOWER_POLL_INTERVAL=30
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: watchtower